<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <title>Systems in C – Performance</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-1d86d68c35eb7061f9efcb6a994936f6.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Performance</h1>
  <p class="subtitle">w6d1</p>

<div class="quarto-title-authors">
</div>

</section>
<section>
<section id="logistics" class="title-slide slide level1 center">
<h1>Logistics</h1>

</section>
<section id="announcements" class="slide level2">
<h2>Announcements</h2>
<ul>
<li><strong>Welcome</strong> to HW/<code>asm</code></li>
<li><strong>Action Items</strong> discussion</li>
</ul>
</section></section>
<section>
<section id="section" class="title-slide slide level1 center">
<h1></h1>
<p>COMP311: COMPUTER ORGANIZATION! Lecture 14: Computer Performance Metrics, More Timing Analysis tinyurl.com/comp311-sp26</p>
</section>
<section id="quiz-topics-logistics-updates" class="slide level2">
<h2>Quiz Topics &amp; Logistics Updates</h2>
<p>■ Encoding/Decoding Basic R-Type &amp; I-Type RISC-V Instructions ■ The ALU, ALU Tracing Don’t forget about the ■ Waveform Diagrams practice problems! ■ Flip flops &amp; Registers (Under assignments tab on website) ■ The Register File ■ Clk-to-Q Delay ■ Basic CPU Performance Metrics (From Today) ■ Timing Analysis Tables (Today)</p>
<p>Undergrad Systems Reading Group!! ☺ ■ Thursdays at 5pm! ■ FB141 ■ Snacks provided! ■ All are welcome!! – No background in CS research necessary ■ If you are interested in being added to the mailing list, send me an email!</p>
<p>COMPUTER PERFORMANCE He said, we need to squeeze the clock</p>
</section>
<section id="why-study-performance" class="slide level2">
<h2>Why study performance?</h2>
<p>● Helps us to make intelligent choices ● Helps us see through marketing hype ● Affects computer organization (pipelining, caches, etc.) ● Why is some hardware faster than others? ● What factors of system performance are hardware related? ○ Do we need a new machine, ○ more memory ○ a better compiler ○ or a new OS? ● How does a machine’s instruction set affect its performance?</p>
</section>
<section id="performance-metrics" class="slide level2">
<h2>Performance Metrics</h2>
<p>■ Latency: time from an input to its corresponding output – How long does it take for my program to run? – How long must I wait after typing <code>return</code> for the result? ■ Throughput: The rate at which new outputs are generated – How many calculations per second? – What is the average execution rate of my program? – How much work is getting done? By running a program on 20 different input By running our program simultaneously on files on the fastest available processor, 20 CPU’s, each assigned an input file, what what performance metric do we improve? performance metric do we improve?</p>
</section>
<section id="what-airplane-has-the-best-performance" class="slide level2">
<h2>What airplane has the best performance?</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 46%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 4%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Aircraft</th>
<th>Passengers</th>
<th>Range (miles)</th>
<th></th>
<th>Speed (mph)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Boeing 737-100</td>
<td></td>
<td>132</td>
<td></td>
<td>630</td>
<td></td>
<td>598</td>
</tr>
<tr class="even">
<td></td>
<td>Boeing 747</td>
<td>470</td>
<td></td>
<td>4150</td>
<td></td>
<td>610</td>
</tr>
<tr class="odd">
<td>BAC/Sud Concorde</td>
<td></td>
<td>101</td>
<td></td>
<td>4000</td>
<td></td>
<td>1350</td>
</tr>
<tr class="even">
<td>Douglas DC-8-50</td>
<td></td>
<td>146</td>
<td></td>
<td>8720</td>
<td></td>
<td>544</td>
</tr>
<tr class="odd">
<td>How much faster is the Concorde than the 747?</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>2.213 X</td>
<td></td>
</tr>
</tbody>
</table>
<p>How much larger is the 747’s capacity than the Concorde? 4.65 X It is roughly 4000 miles from Raleigh to Paris. What is the throughput of the 747 in passengers/hr? The Concorde? 470(610)/4000 = 71.65 pass/hr | What is the latency of the 747? | | | 4000/610 = 6.56 hr/pass | | | | | ——————————- | — | — | ———————— | — | — | — | | The Concorde? | | | 4000/1350 = 2.96 hr/pass | | | |</p>
</section>
<section id="performance-tradeoffs" class="slide level2">
<h2>Performance Tradeoffs</h2>
<p>Maximum Performance: measured by the “number of instructions executed per second” Minimum Cost: determined by the size-of-the-circuit/number-of-components-used plus power/cooling costs 10 10 Best Price/Performance: measured by the ratio of CPU-cost to number of instructions executed per sec. Performance/Watt instructions per second per watt</p>
</section>
<section id="execution-time" class="slide level2">
<h2>Execution Time</h2>
<p>Elapsed Time/Wall Clock Time counts everything (disk and memory accesses, I/O , etc.) a useful number, but often not good for comparison purposes CPU time Doesn’t include I/O or time spent running other Programs can be broken up into system time, and user time Our focus: user CPU time Time spent executing actual instructions of “our” program</p>
</section>
<section id="definition-of-performance" class="slide level2">
<h2>Definition of Performance</h2>
<p>For some program running on machine X, | Performance | | = Program Executions / Time | | | (executions/sec) | | ———– | — | ————————— | — | — | —————- | | | | X | | | X | “X is N times faster than Y” | | Performance | | / Performance | = N | | | — | ———– | — | ————- | — | — | | | | | X | Y | | Problem: Machine A runs a program in 20 seconds Machine B runs the same program in 25 seconds | Performance | | = 1/20 | | Performance | = 1/25 | | ———– | — | —— | — | ———– | —— | | | | A | | | B | Machine A is (1/20)/(1/25) = 1.25 times faster than Machine B</p>
</section>
<section id="program-clock-cycles" class="slide level2">
<h2>Program Clock Cycles</h2>
<p>Instead of reporting execution time in seconds, we can also use cycle counts (sec/program) * (clocks/sec) = clocks/program Clocks are when machine-state changes (synchronous abstraction): time cycle time = time between rising edges of the clock = seconds per clock clock rate (frequency) = clocks per second (1 Hz. = 1 clock/sec) A 200 Mhz. clock has a 1 / ( 2 0 0 * 1 0 6 ) = 5 .0 x 10-9 = 5 nS cycle time Overclocking: improves performance (seconds/program) by decreasing the cycle time (seconds/cycle), while hoping that the functional blocks continue to operate as specified.</p>
</section>
<section id="standard-computer-performance-measures" class="slide level2">
<h2>Standard Computer Performance Measures</h2>
<p>Millions of Instructions per Second Frequency in Hz 1 clocks / second MIPS = 106 clocks / instruction CPI (Average Clocks Per Instruction)</p>
</section>
<section id="how-to-improve-performance" class="slide level2">
<h2>How to improve performance?</h2>
<p>(sec/program) (clocks/sec) = clocks/program 1 clocks / second MIPS = 106 clocks / instruction So, to improve performance (everything else being equal) you can either the # of required clocks for a program, or the clock cycle time or, said another way, the clock rate. the CPI (average clocks per instruction)</p>
</section>
<section id="how-to-improve-performance-1" class="slide level2">
<h2>How to improve performance?</h2>
<p>(sec/program) (clocks/sec) = clocks/program 1 clocks / second MIPS = 106 clocks / instruction So, to improve performance (everything else being equal) you can either Decrease (improve ISA) the # of required clocks for a program, or Decrease the clock cycle time or, said another way, Increase the clock rate. Decrease the CPI (average clocks per instruction)</p>
</section>
<section id="more-timing-analysis" class="slide level2">
<h2>MORE TIMING ANALYSIS</h2>
</section>
<section id="timing" class="slide level2">
<h2>Timing</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Begin 2nd</th>
<th>Begin 3rd</th>
<th></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<p>Begin 1st computation computation computation | 1st | 2nd | | | —————– | ————- | —————- | | computation | computation | 3rd computation | | should be | should be | should be | | completed by the | completed by | | completed by | next rising edge | the next rising | the next rising | | —————– | —————- | —————- | | of the clock | edge of the | edge of the | clock clock</p>
</section>
<section id="timing-1" class="slide level2">
<h2>Timing</h2>
<p>Cycle 1 Cycle 2 Cycle 0 7 + 7 18 + 7 30 + 8</p>
</section>
<section id="starting-state" class="slide level2">
<h2>Starting State</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>0 + 0</th>
<th>0 + 0</th>
<th>0 + 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>0 0 0 0 0 0</p>
</section>
<section id="cycle-0-on-rising-edge" class="slide level2">
<h2>Cycle 0: On rising edge</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>7 + 7</th>
<th>0 + 0</th>
<th>0 + 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>7 0 0 7 0 0</p>
</section>
<section id="cycle-0-after-clk-to-q-delay" class="slide level2">
<h2>Cycle 0: After clk-to-q delay</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>7 + 7</th>
<th>7 + 7</th>
<th>0 + 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>7 7 0 7 0 7</p>
</section>
<section id="cycle-0-after-adder-propagation-delay" class="slide level2">
<h2>Cycle 0: After adder propagation delay</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>7 + 7</th>
<th>7 + 7</th>
<th>0 + 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>7 7 14 7 0 7</p>
</section>
<section id="cycle-1-on-rising-edge" class="slide level2">
<h2>Cycle 1: On rising edge</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>18 + 7</th>
<th>7 + 7</th>
<th>0 + 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>18 7 14 7 0 7</p>
</section>
<section id="cycle-1-after-clk-to-q-delay" class="slide level2">
<h2>Cycle 1: After clk-to-q delay</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>18 + 7</th>
<th>18 + 7</th>
<th>7 + 7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>18 18 14 7 14 7</p>
</section>
<section id="cycle-1-after-adder-propagation-delay" class="slide level2">
<h2>Cycle 1: After adder propagation delay</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>18 + 7</th>
<th>18 + 7</th>
<th>7 + 7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>18 18 25 7 14 7</p>
</section>
<section id="cycle-2-on-rising-edge" class="slide level2">
<h2>Cycle 2: On Rising Edge</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>30 + 8</th>
<th>18 + 7</th>
<th>7 + 7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>30 18 25 8 14 7</p>
</section>
<section id="cycle-2-after-clk-to-q-delay" class="slide level2">
<h2>Cycle 2: After clk-to-q Delay</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>30 + 8</th>
<th>30 + 8</th>
<th>18 + 7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>30 30 25 8 25 8</p>
</section>
<section id="cycle-2-after-adder-propagation-delay" class="slide level2">
<h2>Cycle 2: After Adder Propagation Delay</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>30 + 8</th>
<th>30 + 8</th>
<th>18 + 7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>30 30 38 8 25 8</p>
</section>
<section id="cycle-3-on-rising-edge" class="slide level2">
<h2>Cycle 3: On Rising Edge</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>0 + 0</th>
<th>30 + 8</th>
<th>18 + 7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>30 30 38 8 25 8</p>
</section>
<section id="cycle-3-after-clk-to-q-delay" class="slide level2">
<h2>Cycle 3: After clk-to-q Delay</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>0 + 0</th>
<th>0 + 0</th>
<th>30 + 8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>30 0 38 8 38 0</p>
</section>
<section id="delays" class="slide level2">
<h2>Delays</h2>
<p>■ Adder propagation delay = 600ps ■ Register clk-to-q delay = 50ps ■ These delays are innate properties of the components ■ We can calculate these delays by finding the longest combinational delay ■ We cannot change these values without changing the components</p>
</section>
<section id="clock-period" class="slide level2">
<h2>Clock Period</h2>
<p>■ We can adjust the clock period based on our needs ■ There is a minimum clock period at which the circuit will work properly ■ We can set our clock period to any value &gt;= min clock period</p>
</section>
<section id="ex1-clock-period-700ps-clk-to-q-delay-50ps" class="slide level2">
<h2>Ex1: Clock period = 700ps, clk-to-q delay = 50ps,</h2>
<p>adder propagation delay = 600ps 7 + 7 - next_A next_B curr_A curr_sum prev_sum curr_B</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps" class="slide level2">
<h2>next_A adder propagation delay = 600 ps</h2>
<p>clk-to-q delay is 50ps Cycle 0: 7 + 7 clock period = 700ps | | | | curr_A | curr_sum | | | | — | — | — | —— | ——– | — | — | next_B prev_sum curr_B | 0 ps | | 700 ps | 1400 ps | | 2100 ps | 2800 ps | | —- | — | —— | ——- | ——– | ——— | ———- | | | | | t = 0 | t = 50ps | t = 650ps | t = 700 ps | Starting | | Signal | | A = 7 | A = 7 | A = 7 | A = 18 | | — | —— | — | —– | —– | —– | —— | State | | | | B = 7 | B = 7 | B = 7 | B = 7 | | — | ——– | — | —– | —– | —– | —– | | | next_A | 0 | | | | | | | next_B | 0 | | | | | | | curr_A | 0 | | | | | | | curr_B | 0 | | | | | | | curr_sum | 0 | | | | | | | prev_sum | 0 | | | | |</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-1" class="slide level2">
<h2>next_A adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps | Cycle 0: 7 + 7 | | | | | | | | clock period = 700ps | | ————– | — | — | —— | ——– | — | — | — | ——————– | | | | | curr_A | curr_sum | | | | | next_B prev_sum curr_B | 0 ps | | 700 ps | 1400 ps | | 2100 ps | | 2800 ps | | | —- | — | —— | ——- | ——– | ——- | ——— | ———- | — | | | | | t = 0 | t = 50ps | | t = 650ps | t = 700 ps | | Starting | | Signal | | A = 7 | A = 7 | | A = 7 | | A = 18 | | — | —— | — | —– | —– | — | —– | — | —— | State | | | | B = 7 | B = 7 | | B = 7 | | B = 7 | | — | ——– | — | —– | —– | — | —– | — | —– | | | next_A | 0 | 7 | 7 | | 7 | | 18 | | | next_B | 0 | 7 | 7 | | 7 | | 7 | | | curr_A | 0 | 0 | 7 | | 7 | | 7 | | | curr_B | 0 | 0 | 7 | | 7 | | 7 | | | curr_sum | 0 | 0 | 0 | | 14 | | 14 | | | prev_sum | 0 | 0 | 0 | | 0 | | 0 |</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-2" class="slide level2">
<h2>next_A adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps Cycle 1: 18 + 7 clock period = 700ps | | | | curr_A curr_sum | | | | — | — | — | ————— | — | — | next_B prev_sum curr_B | 0 ps | | 700 ps | 1400 ps | 2100 ps | 2800 ps | | —- | —— | ———- | ———- | ———– | ———– | | | | t = 700 ps | t = 750 ps | t = 1350 ps | t = 1400 ps | | | Signal | A = 18 | A = 18 | A = 18 | A = 30 | | | | B = 7 | B = 7 | B = 7 | B = 8 | next_A 18 next_B 7 curr_A 7 curr_B 7 curr_sum 14 prev_sum 0</p>
</section>
<section id="next_a" class="slide level2">
<h2>next_A</h2>
<p>adder propagation delay = 600 ps clk-to-q delay = 50ps Cycle 1: 18 + 7 clock period = 700ps curr_A curr_sum | | | | next_B | | | | prev_sum | | | | — | — | — | —— | — | — | — | ——– | — | — | curr_B | 0 ps | | 700 ps | | 1400 ps | | 2100 ps | | | 2800 ps | | —- | ——– | —— | ———- | ——- | ———- | ———– | —— | ———– | ——- | | | | | t = 700 ps | | t = 750 ps | t = 1350 ps | | t = 1400 ps | | | | Signal | | A = 18 | | A = 18 | | A = 18 | A = 30 | | | | | | B = 7 | | B = 7 | | B = 7 | | B = 8 | | | next_A | | 18 | | 18 | | 18 | | 30 | | | next_B | | 7 | | 7 | | 7 | | 8 | | | curr_A | | 7 | | 18 | | 18 | | 18 | | | curr_B | | 7 | | 7 | | 7 | | 7 | | | curr_sum | | 14 | | 14 | | 25 | | 25 | | | prev_sum | | 0 | | 14 | | 14 | | 14 |</p>
</section>
<section id="adder-propagation-delay-600-ps" class="slide level2">
<h2>adder propagation delay = 600 ps</h2>
<p>next_A clk-to-q delay = 50ps Cycle 2: 30 + 8 clock period = 700ps curr_A curr_sum | | | | next_B | | prev_sum | | | — | — | — | —— | — | ——– | — | curr_B | 0 ps | | 700 ps | | 1400 ps | 2100 ps | 2800 ps | | —- | ——– | —— | ———– | ———– | ———– | ———– | | | | | t = 1400 ps | t = 1450 ps | t = 2050 ps | t = 2100 ps | | | Signal | | A = 30 | A = 30 | A = 30 | A = 15 | | | | | B = 8 | B = 8 | B = 8 | B = 30 | | | next_A | | 30 | | | | | | next_B | | 8 | | | | | | curr_A | | 18 | | | | | | curr_B | | 7 | | | | | | curr_sum | | 25 | | | | | | prev_sum | | 14 | | | |</p>
</section>
<section id="next_a-1" class="slide level2">
<h2>next_A</h2>
<p>adder propagation delay = 600 ps clk-to-q delay = 50ps | | | | | | | curr_A curr_sum | | | | | | | ————— | — | — | — | —— | — | ————— | — | ——– | — | — | ——————– | | Cycle 2: 30 + 8 | | | | next_B | | | | prev_sum | | | clock period = 700ps | curr_B | 0 ps | | 700 ps | | | 1400 ps | | 2100 ps | | | 2800 ps | | | —- | ——– | —— | ———– | —— | ——- | ———– | ———– | —— | ———– | ——- | — | | | | | t = 1400 ps | | | t = 1450 ps | t = 2050 ps | | t = 2100 ps | | | | | Signal | | | A = 30 | | A = 30 | | A = 30 | | A = 15 | | | | | | | B = 8 | | B = 8 | | B = 8 | | B = 30 | | | | next_A | | | 30 | | 30 | | 30 | | 15 | | | | next_B | | | 8 | | 8 | | 8 | | 30 | | | | curr_A | | | 18 | | 30 | | 30 | | 30 | | | | curr_B | | | 7 | | 8 | | 8 | | 8 | | | | curr_sum | | | 25 | | 25 | | 38 | | 38 | | | | prev_sum | | | 14 | | 25 | | 25 | | 25 | |</p>
</section>
<section id="ex1-clock-period-700ps-clk-to-q-delay-50ps-1" class="slide level2">
<h2>Ex1: Clock period = 700ps, clk-to-q delay = 50ps,</h2>
<p>adder propagation delay = 600ps 7 + 7 - next_A next_B curr_A curr_sum prev_sum curr_B</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-3" class="slide level2">
<h2>next_A adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps Cycle 3: 15 + 30 clock period = 700ps | | | | curr_A curr_sum | | | | | — | — | — | ————— | — | — | — | next_B prev_sum curr_B | 0 ps | | 700 ps | 1400 ps | 2100 ps | 2800 ps | | | —- | — | —— | ——- | ——- | ——- | — | Not a typo! | | | t = 2100 ps | t = 2150 ps | t = 2750 ps | t = 2800 ps | | | — | — | ———– | ———– | ———– | ———– | — | What will | | Signal | A = 15 | A = 15 | A = 20 | A = 20 | | | — | —— | —— | —— | —— | —— | — | happen in | | | B = 30 | B = 30 | B = 30 | B = 30 | this case? | | — | — | —— | —— | —— | —— | ———- | next_A 15 next_B 30 curr_A 30 curr_B 8 curr_sum 38 prev_sum 25</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-4" class="slide level2">
<h2>| | | | next_A | | | adder propagation delay = 600 ps | |</h2>
<div class="line-block">— | — | — | —— | — | — | ——————————– | — |</div>
<p>clk-to-q delay = 50ps Cycle 3: 15 + 30 clock period = 700ps curr_A curr_sum | | | | next_B | | prev_sum | | | | — | — | — | —— | — | ——– | — | — | curr_B | 0 ps | | 700 ps | | 1400 ps | 2100 ps | 2800 ps | | | —- | —— | ———– | —— | ———– | ———– | ———– | ———— | | | | t = 2100 ps | | t = 2150 ps | t = 2750 ps | t = 2800 ps | Not a typo! | | | Signal | | A = 15 | A = 15 | A = 20 | A = 20 | | What will | | | | B = 30 | B = 30 | B = 30 | B = 30 | | | — | — | — | —— | —— | —— | —— | — | happen in this case? | | next_A | | 15 | 15 | 20 | 20 | | | — | ——– | — | — | — | — | — | — | | | next_B | | 30 | 30 | 30 | 30 | | | | curr_A | | 30 | 15 | 15 | 15 | | | | curr_B | | 8 | 30 | 30 | 30 | | | | curr_sum | | 38 | 38 | 45 | 45 | | | | prev_sum | | 25 | 38 | 38 | 38 | |</p>
</section>
<section id="input-a-updating-at-t-2750ps" class="slide level2">
<h2>Input A updating at t = 2750ps</h2>
<p>■ Our addition will work the same as before! ■ The register prevents the value of A from moving forward until the rising edge of the clock ■ We can update the inputs anytime from t = 2150ps to t = 2800ps – (aka until the next rising edge) ■ The value will simply just stay at the input of the register until the rising edge of the clock</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-5" class="slide level2">
<h2>| | | | next_A | | | adder propagation delay = 600 ps |</h2>
<div class="line-block">— | — | — | —— | — | — | ——————————– |</div>
<p>clk-to-q delay = 50ps Cycle 4: 20 + 30 clock period = 700ps | | | | | curr_A curr_sum | | | | — | — | — | — | ————— | — | — | next_B prev_sum curr_B | 0 ps | | 700 ps | | 1400 ps | 2100 ps | 2800 ps | | —- | ——– | —— | ———– | ———– | ———– | ———– | | | | | t = 2800 ps | t = 2850 ps | t = 3450 ps | t = 3500 ps | | | Signal | | A = 20 | A = 20 | A = 20 | A = 0 | | | | | B = 30 | B = 30 | B = 30 | B = 0 | | | next_A | | 20 | | | | | | next_B | | 30 | | | | | | curr_A | | 15 | | | | | | curr_B | | 30 | | | | | | curr_sum | | 45 | | | | | | prev_sum | | 38 | | | |</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-6" class="slide level2">
<h2>| | | | next_A | | | | adder propagation delay = 600 ps | |</h2>
<div class="line-block">— | — | — | —— | — | — | — | ——————————– | — |</div>
<p>clk-to-q delay = 50ps Cycle 4: 20 + 30 clock period = 700ps curr_A curr_sum | | | | next_B | | | prev_sum | | | | — | — | — | —— | — | — | ——– | — | — | curr_B | 0 ps | | 700 ps | | 1400 ps | | 2100 ps | | 2800 ps | | —- | ——– | —— | ———– | ——- | ———– | ———– | ———– | ——- | | | | | t = 2800 ps | | t = 2850 ps | t = 3450 ps | t = 3500 ps | | | | Signal | | A = 20 | | A = 20 | A = 20 | | A = 0 | | | | | B = 30 | | B = 30 | B = 30 | | B = 0 | | | next_A | | 20 | | 20 | 20 | | 0 | | | next_B | | 30 | | 30 | 30 | | 0 | | | curr_A | | 15 | | 20 | 20 | | 20 | | | curr_B | | 30 | | 30 | 30 | | 30 | | | curr_sum | | 45 | | 45 | 50 | | 50 | | | prev_sum | | 38 | | 45 | 45 | | 45 |</p>
</section>
<section id="clock-period-700ps" class="slide level2">
<h2>Clock Period = 700ps</h2>
<table class="caption-top">
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>0 ps</th>
<th></th>
<th>700 ps</th>
<th></th>
<th>1400 ps</th>
<th></th>
<th>2100 ps</th>
<th></th>
<th>2800 ps</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td></td>
<td>18 + 7</td>
<td></td>
<td>30 + 8</td>
<td></td>
<td>15 + 30</td>
<td></td>
<td>20 + 30</td>
</tr>
</tbody>
</table>
<p>clk-to-q delay = 50ps adder propagation delay = 600ps idle time = 50ps</p>
</section>
<section id="ex2-clock-period-650ps-clk-to-q-delay-50ps" class="slide level2">
<h2>Ex2: Clock period = 650ps, clk-to-q delay = 50ps,</h2>
<p>adder propagation delay = 600ps 7 + 7 - next_A next_B curr_A curr_sum prev_sum curr_B</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-7" class="slide level2">
<h2>next_A adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps Cycle 0: 7 + 7 clock period = 650ps curr_A curr_sum next_B prev_sum curr_B | 0 ps | | 650 ps | 1300 ps | 1950 ps | 2600 ps | | —- | —— | ————– | ——- | ——– | ———- | | | | | t = 0 | t = 50ps | t = 650 ps | | | Signal | Starting State | A = 7 | A = 7 | A = 18 | | | | | B = 7 | B = 7 | B = 7 | next_A 0 next_B 0 curr_A 0 curr_B 0 curr_sum 0 prev_sum 0</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-8" class="slide level2">
<h2>| | | next_A | | | | | adder propagation delay = 600 ps |</h2>
<div class="line-block">— | — | —— | — | — | — | — | ——————————– |</div>
<p>clk-to-q delay = 50ps Cycle 0: 7 + 7 clock period = 650ps | | | | | curr_A | curr_sum | | | | — | — | —— | — | —— | ——– | ——– | — | | | | next_B | | | | prev_sum | | curr_B | 0 ps | | 650 ps | | 1300 ps | | 1950 ps | 2600 ps | | —- | ——– | ————– | — | ——- | —– | ——– | ———- | | | | | | | t = 0 | t = 50ps | t = 650 ps | | | Signal | Starting State | | | A = 7 | A = 7 | A = 18 | | | | | | | B = 7 | B = 7 | B = 7 | | | next_A | | 0 | | 7 | 7 | 18 | | | next_B | | 0 | | 7 | 7 | 7 | | | curr_A | | 0 | | 0 | 7 | 7 | | | curr_B | | 0 | | 0 | 7 | 7 | | | curr_sum | | 0 | | 0 | 0 | 14 | | | prev_sum | | 0 | | 0 | 0 | 0 |</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-9" class="slide level2">
<h2>| | next_A | | | | adder propagation delay = 600 ps | |</h2>
<div class="line-block">— | —— | — | — | — | ——————————– | — |</div>
<p>clk-to-q delay = 50ps Cycle 1: 18 + 7 clock period = 650ps curr_A curr_sum | | next_B | | | | prev_sum | | | — | —— | — | — | — | ——– | — | curr_B | 0 ps | 650 ps | 1300 ps | | 1950 ps | | 2600 ps | | —- | ——– | ———- | ———- | ——- | ———– | ——- | | | | t = 650 ps | t = 700 ps | | t = 1300 ps | | | | Signal | A = 18 | A = 18 | | A = 30 | | | | | B = 7 | B = 7 | | B = 8 | | | | next_A | 18 | | | | | | | next_B | 7 | | | | | | | curr_A | 7 | | | | | | | curr_B | 7 | | | | | | | curr_sum | 14 | | | | | | | prev_sum | 0 | | | | |</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-10" class="slide level2">
<h2>| | next_A | | | | adder propagation delay = 600 ps | |</h2>
<div class="line-block">— | —— | — | — | — | ——————————– | — |</div>
<p>clk-to-q delay = 50ps Cycle 1: 18 + 7 clock period = 650ps curr_A curr_sum | | next_B | | | | prev_sum | | | — | —— | — | — | — | ——– | — | curr_B | 0 ps | 650 ps | 1300 ps | | 1950 ps | | 2600 ps | | —- | ——– | ———- | ———- | ——- | ———– | ——- | | | | t = 650 ps | t = 700 ps | | t = 1300 ps | | | | Signal | A = 18 | A = 18 | | A = 30 | | | | | B = 7 | B = 7 | | B = 8 | | | | next_A | 18 | 18 | | 30 | | | | next_B | 7 | 7 | | 8 | | | | curr_A | 7 | 18 | | 18 | | | | curr_B | 7 | 7 | | 7 | | | | curr_sum | 14 | 14 | | 25 | | | | prev_sum | 0 | 14 | | 14 | |</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-11" class="slide level2">
<h2>| | next_A | | | | adder propagation delay = 600 ps | |</h2>
<div class="line-block">— | —— | — | — | — | ——————————– | — |</div>
<p>clk-to-q delay = 50ps Cycle 2: 30 + 8 clock period = 650ps curr_A curr_sum | | next_B | | | prev_sum | | | | — | —— | — | — | ——– | — | — | curr_B | 0 ps | 650 ps | 1300 ps | | 1950 ps | | 2600 ps | | —- | ——– | ———– | ———– | ——- | ———– | ——- | | | | t = 1300 ps | t = 1350 ps | | t = 1950 ps | | | | Signal | A = 30 | A = 30 | | A = 15 | | | | | B = 8 | B = 8 | | B = 30 | | | | next_A | 30 | | | | | | | next_B | 8 | | | | | | | curr_A | 18 | | | | | | | curr_B | 7 | | | | | | | curr_sum | 25 | | | | | | | prev_sum | 14 | | | | |</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-12" class="slide level2">
<h2>| | next_A | | | | | | adder propagation delay = 600 ps | |</h2>
<div class="line-block">— | —— | — | — | — | — | — | ——————————– | — |</div>
<p>clk-to-q delay = 50ps Cycle 2: 30 + 8 clock period = 650ps | | | | curr_A | curr_sum | | | | | | — | —— | — | —— | ——– | ——– | — | — | — | | | next_B | | | | prev_sum | | | | curr_B | 0 ps | 650 ps | | 1300 ps | | 1950 ps | | | 2600 ps | | —- | ——– | ———– | ——- | ———– | ——- | ———– | —— | ——- | | | | t = 1300 ps | | t = 1350 ps | | t = 1950 ps | | | | | Signal | | A = 30 | A = 30 | | | A = 15 | | | | | | B = 8 | | B = 8 | B = 30 | | | | | next_A | | 30 | | 30 | | 15 | | | | next_B | | 8 | | 8 | | 30 | | | | curr_A | | 18 | | 30 | | 30 | | | | curr_B | | 7 | | 8 | | 8 | | | | curr_sum | | 25 | | 25 | | 38 | | | | prev_sum | | 14 | | 25 | | 25 | |</p>
</section>
<section id="adder-propagation-delay-600-ps-1" class="slide level2">
<h2>adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps Cycle 3: 15 + 30 clock period = 650ps | 0 ps | 650 ps | 1300 ps | | 1950 ps | | 2600 ps | | —- | ——– | ———– | ———– | ——- | ———– | ——- | | | | t = 1950 ps | t = 2000 ps | | t = 2600 ps | | | | Signal | A = 15 | A = 15 | | A = 20 | | | | | B = 30 | B = 30 | | B = 30 | | | | next_A | 15 | | | | | | | next_B | 30 | | | | | | | curr_A | 30 | | | | | | | curr_B | 8 | | | | | | | curr_sum | 38 | | | | | | | prev_sum | 25 | | | | |</p>
</section>
<section id="adder-propagation-delay-600-ps-2" class="slide level2">
<h2>adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps Cycle 3: 15 + 30 clock period = 650ps | 0 ps | 650 ps | 1300 ps | | 1950 ps | | 2600 ps | | —- | ——– | ———– | ———– | ——- | ———– | ——- | | | | t = 1950 ps | t = 2000 ps | | t = 2600 ps | | | | Signal | A = 15 | A = 15 | | A = 20 | | | | | B = 30 | B = 30 | | B = 30 | | | | next_A | 15 | 15 | | 20 | | | | next_B | 30 | 30 | | 30 | | | | curr_A | 30 | 15 | | 15 | | | | curr_B | 8 | 30 | | 30 | | | | curr_sum | 38 | 38 | | 45 | | | | prev_sum | 25 | 38 | | 38 | |</p>
</section>
<section id="adder-propagation-delay-600-ps-3" class="slide level2">
<h2>adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps Cycle 4: 20 + 30 clock period = 650ps | 0 ps | 650 ps | | 1300 ps | 1950 ps | 2600 ps | | —- | ——– | ———– | ———– | ———– | ———– | | | | t = 2600 ps | t = 2650 ps | t = 3250 ps | t = 3300 ps | | | Signal | A = 20 | A = 20 | A = 0 | A = 0 | | | | B = 30 | B = 30 | B = 0 | B = 0 | | | next_A | 20 | | | | | | next_B | 30 | | | | | | curr_A | 15 | | | | | | curr_B | 30 | | | | | | curr_sum | 45 | | | | | | prev_sum | 38 | | | |</p>
</section>
<section id="adder-propagation-delay-600-ps-4" class="slide level2">
<h2>adder propagation delay = 600 ps</h2>
<p>clk-to-q delay = 50ps Cycle 4: 20 + 30 clock period = 650ps | 0 ps | | 650 ps | | 1300 ps | | 1950 ps | | | 2600 ps | | —- | ——– | —— | ———– | ——- | ———– | ———– | —– | ———– | ——- | | | | | t = 2600 ps | | t = 2650 ps | t = 3250 ps | | t = 3300 ps | | | | Signal | | A = 20 | | A = 20 | | A = 0 | | A = 0 | | | | | B = 30 | | B = 30 | | B = 0 | | B = 0 | | | next_A | | 20 | | 20 | | 0 | | 0 | | | next_B | | 30 | | 30 | | 0 | | 0 | | | curr_A | | 15 | | 20 | | 20 | | 0 | | | curr_B | | 30 | | 30 | | 30 | | 0 | | | curr_sum | | 45 | | 45 | | 50 | | 50 | | | prev_sum | | 38 | | 45 | | 45 | | 50 |</p>
</section>
<section id="clock-period-650ps" class="slide level2">
<h2>Clock Period = 650ps</h2>
<table class="caption-top">
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>0 ps</th>
<th></th>
<th>650 ps</th>
<th></th>
<th>1300 ps</th>
<th></th>
<th>1950 ps</th>
<th></th>
<th>2600 ps</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>7 + 7</td>
<td></td>
<td>18 + 7</td>
<td></td>
<td>30 + 8</td>
<td></td>
<td>15 + 30</td>
<td></td>
<td>20 + 30</td>
</tr>
</tbody>
</table>
<p>clk-to-q delay = 50ps adder propagation delay = 600ps</p>
</section>
<section id="comparing-clock-periods" class="slide level2">
<h2>Comparing Clock Periods</h2>
<p>■ Our circuit functioned correctly at both of the clock periods we tried – 650ps and 700ps ■ Our five addition operations finished faster when we set our clock period to 650ps compared to 700ps</p>
</section>
<section id="ex3-clock-period-500ps-clk-to-q-delay-50ps" class="slide level2">
<h2>Ex3: Clock period = 500ps, clk-to-q delay = 50ps,</h2>
<p>adder propagation delay = 600ps 7 + 7 - next_A next_B curr_A curr_sum prev_sum curr_B</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-13" class="slide level2">
<h2>| | | next_A | | | adder propagation delay = 600 ps | |</h2>
<div class="line-block">— | — | —— | — | — | ——————————– | — |</div>
<p>clk-to-q delay is 50ps Cycle 0 &amp; 1: 7 + 7 clock period = 500ps curr_A curr_sum | | | next_B | | | prev_sum | | | — | — | —— | — | — | ——– | — | curr_B | 0 ps | 500 ps | 1000 ps | | 1500 ps | | 2000 ps | | —— | ————– | ——- | ——– | ——- | ——— | ——— | | | | t = 0 | t = 50ps | | t = 500ps | t = 550ps | | Signal | Starting State | A = 7 | A = 7 | | A = 18 | A = 18 | | | | B = 7 | B = 7 | | B = 7 | B = 7 | next_A 0 next_B 0 curr_A 0 curr_B 0 curr_sum 0 prev_sum 0</p>
</section>
<section id="next_a-adder-propagation-delay-600-ps-14" class="slide level2">
<h2>| | | next_A | | | | adder propagation delay = 600 ps | | |</h2>
<div class="line-block">— | — | —— | — | — | — | ——————————– | — | — |</div>
<p>clk-to-q delay is 50ps | Cycle 0 &amp; 1: 7 + 7 | | | | | | | | clock period = 500ps | | —————— | — | — | — | — | — | — | — | ——————– | curr_A curr_sum | | | next_B | | | | prev_sum | | | | — | — | —— | — | — | — | ——– | — | — | curr_B | 0 ps | | 500 ps | 1000 ps | | 1500 ps | | 2000 ps | | | ——– | ————– | —— | ——- | ——– | ——- | ——— | ——— | —— | | | | | t = 0 | t = 50ps | | t = 500ps | t = 550ps | | | Signal | Starting State | | A = 7 | A = 7 | | A = 18 | | A = 18 | | | | | B = 7 | B = 7 | | B = 7 | | B = 7 | | next_A | | 0 | 7 | 7 | | 18 | | 18 | | next_B | | 0 | 7 | 7 | | 7 | | 7 | | curr_A | | 0 | 0 | 7 | | 7 | | 18 | | curr_B | | 0 | 0 | 7 | | 7 | | 7 | | curr_sum | | 0 | 0 | 0 | | ?? | | ?? | | prev_sum | | 0 | 0 | 0 | | 0 | | ?? |</p>
</section>
<section id="clock-period-500ps" class="slide level2">
<h2>Clock Period = 500ps</h2>
<p>0 ps 500 ps 1000 ps 1500 ps 2000 ps 7 + 7 clk-to-q delay = 50ps adder propagation delay = 600ps</p>
</section>
<section id="clock-period-500ps-1" class="slide level2">
<h2>Clock Period = 500ps</h2>
<p>■ Our circuit does not operate correctly with a period of 500ps ■ Why? – The adder cannot finish its operation before the next rising edge of the clock – The output register ends up reading garbage</p>
</section>
<section id="take-away-how-to-determine-the-minimum-clock-period" class="slide level2">
<h2>Take Away: How to determine the minimum clock period?</h2>
<p>min clock period = clk-to-q delay of the input registers + adder propagation delay</p>
</section>
<section id="in-general" class="slide level2">
<h2>In General…</h2>
<p>min clock period = clk-to-q delay of the input registers + longest combinational path</p>
</section>
<section id="min-clock-period" class="slide level2">
<h2>Min Clock Period</h2>
<p>■ Why do we not include the clk-to-q delay of the output register when determining the min clock period?</p>
</section>
<section id="min-clock-period-1" class="slide level2">
<h2>Min Clock Period</h2>
<p>■ Why do we not include the clk-to-q delay of the output register when determining the min clock period? In one clock cycle, we need to read the input registers, compute their sum, and ensure the value is ready for the output register before the next rising edge of the clock. The value will not pass through the output register until the next rising edge of the clock.</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="index.html">Home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>